-- 코드를 입력하세요
-- IN에는 있는데 out에는 없는 갓ㅂ 
SELECT AI.NAME, AI.DATETIME
FROM ANIMAL_INS AI
LEFT JOIN ANIMAL_OUTS AO
ON AI.ANIMAL_ID = AO.ANIMAL_ID
WHERE AO.DATETIME IS NULL
ORDER BY AI.DATETIME ASC
LIMIT 3
#상위 3개